services:
  db:
    image: postgres:15-alpine
    container_name: grocery-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grocery
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: grocery-api
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      # Overriding the DB_HOST to match the service name 'db' inside the docker network
      DB_HOST: db

volumes:
  postgres_data:
